const express = require('express')
const bodyParser = require('body-parser')
const db = require('./config/config')
const Empleado = require('./models/empleado')
const Turno = require('./models/turnos')
const Extra = require('./models/extras')
const Dia = require('./models/dias')
const ValorTurno = require('./models/valor-turno')
const Puesto = require('./models/puesto')
const Local = require('./models/local')

const cors = require('cors')
const routes = require('./routes')
const app = express()
app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())

db.sync()
    .then(() => console.log('conectado'))
    .catch(error => console.log(error))
app.use(cors())

app.use('/', routes())
app.listen(5000)